# Generated by Django 3.2 on 2021-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('opentime', models.DateTimeField(blank=True)),
                ('open', models.FloatField(blank=True)),
                ('high', models.FloatField(blank=True)),
                ('low', models.FloatField(blank=True)),
                ('close', models.FloatField(blank=True)),
                ('volume', models.FloatField(blank=True)),
                ('closetime', models.DateTimeField(blank=True)),
                ('q_a_s', models.FloatField(blank=True)),
                ('n_a_t', models.PositiveIntegerField(blank=True)),
                ('t_b_b', models.FloatField(blank=True)),
                ('t_b_q', models.FloatField(blank=True)),
                ('ignore', models.PositiveIntegerField(blank=True)),
                ('predict24h', models.FloatField(blank=True)),
            ],
        ),
    ]
