# Generated by Django 3.2 on 2022-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predict_grow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('pair', models.CharField(blank=True, max_length=50)),
                ('nn', models.CharField(blank=True, max_length=250)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('value', models.FloatField(blank=True)),
            ],
        ),
    ]
