# Generated by Django 3.2 on 2022-04-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperapp', '0003_alter_predict_grow_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict_grow',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predict_grow',
            name='trueorfalse',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
